import fs from 'node:fs';
const read=p=>fs.readFileSync(p,'utf8');const router=read('src/GameRouter.sol'),vault=read('src/MoncorVault.sol'),fixed=read('src/logic/FixedGameLogic.sol'),variable=read('src/logic/VariableGameLogic.sol'),verifier=read('src/SettlementVerifier.sol'),types=read('src/types/MoncorTypes.sol'),quoteHash=read('src/libraries/QuoteHashing.sol'),settlementHash=read('src/libraries/SettlementHashing.sol'),deploy=read('script/DeployMonadTestnet.s.sol');
const checks=[
 ['chain assertion',router.includes('TARGET_CHAIN_ID=10143')&&deploy.includes('block.chainid!=10143')],['native exact value',router.includes('q.asset!=address(0)||msg.value!=q.stake')],['fixed exact domain',fixed.includes('h != 60 && h != 180 && h != 300 && h != 600')],['variable exact bounds',variable.includes('h < 10 || h > 60')],['quote replay',router.includes('consumedQuoteId')&&router.includes('consumedNonce')],
 ['fee included in exposure',router.includes('uint256(a.payout)+w.fee>w.maxPayout')&&vault.includes('uint256(payout)+fee<=reserve')],['fees protected',vault.includes('claimableLiability+refundableLiability+reservedPayout+protocolFeesAccrued')],['accounting views',vault.includes('function protectedBalance()')&&vault.includes('function freeReserve()')&&vault.includes('function withdrawableProtocolFees()')],
 ['historical signer sets',verifier.includes('signerSets[a.signerSetVersion]')&&types.includes('uint64 signerSetVersion')],['exact threshold',verifier.includes('sigs.length!=set.threshold')],['sorted unique signatures',verifier.includes('s<=prev')],['terms hash binding',types.includes('bytes32 termsHash')&&quoteHash.includes('refundAvailableAt')&&settlementHash.includes('bytes32 termsHash')&&router.includes('a.termsHash!=w.termsHash')],
 ['permissionless timeout refund',router.includes('function triggerTimeoutRefund')&&!router.match(/function triggerTimeoutRefund[^\{]+onlyRole/)],['loss closes',types.includes('CLOSED')&&router.includes('WagerState.CLOSED')],['granular pauses preserve exits',router.includes('settlementPaused')&&vault.includes('feeWithdrawalPaused')&&!router.match(/function (claim|claimRefund|triggerTimeoutRefund)[^\{]+whenNotPaused/)],
 ['bounded quote timing',router.includes('maxQuoteTtl')&&router.includes('maxStartDelay')&&router.includes('q.expiresAt>q.startAt')],['atomic deployment wiring',deploy.includes('vault.configureRouter')&&deploy.includes('verifier.configureRouter')&&deploy.includes('renounceRole')]
];
for(const [n,ok] of checks){console.log(`STATIC ${ok?'PASS':'FAIL'} ${n}`);if(!ok)process.exitCode=1;}
