// SPDX-License-Identifier: MIT
pragma solidity 0.8.36;
import {AccessControl} from "@openzeppelin/contracts/access/AccessControl.sol";import {Pausable} from "@openzeppelin/contracts/utils/Pausable.sol";import {ReentrancyGuard} from "@openzeppelin/contracts/utils/ReentrancyGuard.sol";import {EIP712} from "@openzeppelin/contracts/utils/cryptography/EIP712.sol";import {ECDSA} from "@openzeppelin/contracts/utils/cryptography/ECDSA.sol";
import {MoncorTypes} from "./types/MoncorTypes.sol";import {QuoteHashing} from "./libraries/QuoteHashing.sol";import {FixedGameLogic} from "./logic/FixedGameLogic.sol";import {VariableGameLogic} from "./logic/VariableGameLogic.sol";import {IMoncorVault} from "./interfaces/IMoncorVault.sol";import {ISettlementVerifier} from "./interfaces/ISettlementVerifier.sol";

contract GameRouter is AccessControl,Pausable,ReentrancyGuard,EIP712 {
 uint256 public constant TARGET_CHAIN_ID=10143;uint64 public constant MAX_CONFIG_BOUND=30 days;bytes32 public constant QUOTE_SIGNER_ROLE=keccak256("QUOTE_SIGNER_ROLE");bytes32 public constant PAUSER_ROLE=keccak256("PAUSER_ROLE");bytes32 public constant SETTLEMENT_PAUSER_ROLE=keccak256("SETTLEMENT_PAUSER_ROLE");bytes32 public constant DISPUTE_ROLE=keccak256("DISPUTE_ROLE");
 IMoncorVault public immutable vault;ISettlementVerifier public immutable verifier;uint64 public immutable maxQuoteTtl;uint64 public immutable maxStartDelay;bool public settlementPaused;
 mapping(bytes32=>MoncorTypes.Wager) private wagers;mapping(address=>mapping(bytes32=>bool)) public consumedQuoteId;mapping(address=>mapping(uint256=>bool)) public consumedNonce;
 error WrongChain(uint256,uint256);error WalletMismatch(address,address);error QuoteExpired(uint64,uint64);error QuoteAlreadyConsumed(bytes32);error NonceAlreadyUsed(address,uint256);error InvalidSignature();error InvalidTimestamp(uint64,uint64);error InvalidTerms();error InvalidState(bytes32,uint8);error SettlementMismatch();error NotBeneficiary();error SettlementIsPaused();
 event WagerAccepted(bytes32 indexed wagerId,bytes32 indexed quoteId,address indexed player,bytes32 termsHash,uint64 signerSetVersion,uint64 refundAvailableAt);event QuoteConsumed(bytes32 indexed quoteId,address indexed wallet,uint256 nonce);event WagerSettled(bytes32 indexed wagerId,uint8 outcome,uint128 payout,uint128 fee);event WagerClosed(bytes32 indexed wagerId,uint8 outcome,uint128 fee);event DisputeOpened(bytes32 indexed wagerId,bytes32 reasonHash);event RefundAccrued(bytes32 indexed wagerId,address indexed player,uint128 amount);event Claimed(bytes32 indexed wagerId,address indexed player,bool refund);event SettlementPauseChanged(bool paused);
 constructor(address admin,address vault_,address verifier_,address quoteSigner,uint64 maxQuoteTtl_,uint64 maxStartDelay_) EIP712("Moncor GameRouter","1"){require(admin!=address(0)&&vault_!=address(0)&&verifier_!=address(0)&&quoteSigner!=address(0)&&maxQuoteTtl_>0&&maxQuoteTtl_<=MAX_CONFIG_BOUND&&maxStartDelay_>0&&maxStartDelay_<=MAX_CONFIG_BOUND);vault=IMoncorVault(vault_);verifier=ISettlementVerifier(verifier_);maxQuoteTtl=maxQuoteTtl_;maxStartDelay=maxStartDelay_;_grantRole(DEFAULT_ADMIN_ROLE,admin);_grantRole(PAUSER_ROLE,admin);_grantRole(SETTLEMENT_PAUSER_ROLE,admin);_grantRole(DISPUTE_ROLE,admin);_grantRole(QUOTE_SIGNER_ROLE,quoteSigner);}
 function pause() external onlyRole(PAUSER_ROLE){_pause();}function unpause() external onlyRole(PAUSER_ROLE){_unpause();}function setSettlementPaused(bool value) external onlyRole(SETTLEMENT_PAUSER_ROLE){settlementPaused=value;emit SettlementPauseChanged(value);}
 function acceptQuote(MoncorTypes.Quote calldata q,bytes calldata sig) external payable whenNotPaused nonReentrant returns(bytes32 id){if(block.chainid!=TARGET_CHAIN_ID)revert WrongChain(block.chainid,TARGET_CHAIN_ID);if(msg.sender!=q.wallet)revert WalletMismatch(q.wallet,msg.sender);if(q.asset!=address(0)||msg.value!=q.stake||q.stake==0||q.maxPayout<q.stake||q.fee>q.maxPayout||q.marketId==0||q.policyId==0||q.quoteId==0)revert InvalidTerms();
  if(q.issuedAt>block.timestamp||block.timestamp>q.expiresAt)revert QuoteExpired(q.expiresAt,uint64(block.timestamp));if(q.expiresAt<q.issuedAt||q.expiresAt>q.startAt||q.expiresAt-q.issuedAt>maxQuoteTtl||q.startAt<block.timestamp||q.startAt-block.timestamp>maxStartDelay||q.settlementAt<=q.startAt||q.settlementAt-q.startAt!=q.horizonSeconds||q.refundAvailableAt<=q.settlementAt||q.refundAvailableAt-q.settlementAt>maxStartDelay)revert InvalidTimestamp(q.startAt,q.settlementAt);
  if(q.signerSetVersion!=verifier.signerSetVersion()||!verifier.signerSetActive(q.signerSetVersion))revert InvalidTerms();if(q.mode==uint8(MoncorTypes.GameMode.FIXED))FixedGameLogic.validate(q.horizonSeconds);else if(q.mode==uint8(MoncorTypes.GameMode.VARIABLE))VariableGameLogic.validate(q.horizonSeconds,q.selection);else revert InvalidTerms();if(consumedQuoteId[q.wallet][q.quoteId])revert QuoteAlreadyConsumed(q.quoteId);if(consumedNonce[q.wallet][q.nonce])revert NonceAlreadyUsed(q.wallet,q.nonce);
  bytes32 termsHash=QuoteHashing.hash(q);address signer=ECDSA.recover(_hashTypedDataV4(termsHash),sig);if(!hasRole(QUOTE_SIGNER_ROLE,signer))revert InvalidSignature();consumedQuoteId[q.wallet][q.quoteId]=true;consumedNonce[q.wallet][q.nonce]=true;id=keccak256(abi.encode(address(this),termsHash));if(wagers[id].state!=MoncorTypes.WagerState.NONE)revert QuoteAlreadyConsumed(q.quoteId);
  wagers[id]=MoncorTypes.Wager(q.wallet,q.asset,q.quoteId,q.marketId,q.policyId,termsHash,q.policyVersion,q.signerSetVersion,q.startAt,q.settlementAt,q.refundAvailableAt,uint64(block.timestamp),q.stake,q.maxPayout,q.fee,q.targetPrice,q.priceScale,q.horizonSeconds,MoncorTypes.GameMode(q.mode),q.selection,MoncorTypes.WagerState.ACTIVE);vault.lockStake{value:msg.value}(id,q.wallet,q.asset,q.stake,q.maxPayout);emit QuoteConsumed(q.quoteId,q.wallet,q.nonce);emit WagerAccepted(id,q.quoteId,q.wallet,termsHash,q.signerSetVersion,q.refundAvailableAt);}
 function submitSettlement(MoncorTypes.SettlementAttestation calldata a,bytes[] calldata sigs) external nonReentrant{if(settlementPaused)revert SettlementIsPaused();MoncorTypes.Wager storage w=wagers[a.wagerId];if(w.state!=MoncorTypes.WagerState.ACTIVE)revert InvalidState(a.wagerId,uint8(w.state));if(block.timestamp<w.settlementAt||a.termsHash!=w.termsHash||a.policyId!=w.policyId||a.policyVersion!=w.policyVersion||a.signerSetVersion!=w.signerSetVersion||a.startAt!=w.startAt||a.settlementAt!=w.settlementAt||a.priceScale!=w.priceScale||a.evidenceHash==0||a.outcome>uint8(MoncorTypes.Outcome.REFUND)||uint256(a.payout)+w.fee>w.maxPayout)revert SettlementMismatch();verifier.verifyAndConsume(a,sigs);
  if(a.outcome==uint8(MoncorTypes.Outcome.REFUND)){if(a.payout!=0)revert SettlementMismatch();w.state=MoncorTypes.WagerState.REFUNDABLE;vault.accrueRefund(a.wagerId,w.player,w.stake);emit RefundAccrued(a.wagerId,w.player,w.stake);}else if(a.outcome==uint8(MoncorTypes.Outcome.LOSS)){if(a.payout!=0)revert SettlementMismatch();w.state=MoncorTypes.WagerState.CLOSED;vault.accruePayout(a.wagerId,w.player,0,w.fee);emit WagerClosed(a.wagerId,a.outcome,w.fee);}else{if(a.payout==0)revert SettlementMismatch();w.state=MoncorTypes.WagerState.SETTLED;vault.accruePayout(a.wagerId,w.player,a.payout,w.fee);emit WagerSettled(a.wagerId,a.outcome,a.payout,w.fee);}}
 function triggerTimeoutRefund(bytes32 id) external nonReentrant{MoncorTypes.Wager storage w=wagers[id];if(w.state!=MoncorTypes.WagerState.ACTIVE&&w.state!=MoncorTypes.WagerState.DISPUTED)revert InvalidState(id,uint8(w.state));if(block.timestamp<w.refundAvailableAt)revert InvalidTimestamp(w.settlementAt,w.refundAvailableAt);w.state=MoncorTypes.WagerState.REFUNDABLE;vault.accrueRefund(id,w.player,w.stake);emit RefundAccrued(id,w.player,w.stake);}
 function openDispute(bytes32 id,bytes32 reason) external onlyRole(DISPUTE_ROLE){MoncorTypes.Wager storage w=wagers[id];if(w.state!=MoncorTypes.WagerState.ACTIVE)revert InvalidState(id,uint8(w.state));w.state=MoncorTypes.WagerState.DISPUTED;emit DisputeOpened(id,reason);}function resolveRefund(bytes32 id,bytes32) external onlyRole(DISPUTE_ROLE){MoncorTypes.Wager storage w=wagers[id];if(w.state!=MoncorTypes.WagerState.DISPUTED)revert InvalidState(id,uint8(w.state));w.state=MoncorTypes.WagerState.REFUNDABLE;vault.accrueRefund(id,w.player,w.stake);emit RefundAccrued(id,w.player,w.stake);}
 function claim(bytes32 id) external{_claim(id,false);}function claimRefund(bytes32 id) external{_claim(id,true);}function _claim(bytes32 id,bool refund) internal nonReentrant{MoncorTypes.Wager storage w=wagers[id];if(msg.sender!=w.player)revert NotBeneficiary();MoncorTypes.WagerState expected=refund?MoncorTypes.WagerState.REFUNDABLE:MoncorTypes.WagerState.SETTLED;if(w.state!=expected)revert InvalidState(id,uint8(w.state));w.state=refund?MoncorTypes.WagerState.REFUNDED:MoncorTypes.WagerState.CLAIMED;vault.claimTo(id,w.player);emit Claimed(id,w.player,refund);}function getWager(bytes32 id) external view returns(MoncorTypes.Wager memory){return wagers[id];}
}
