// SPDX-License-Identifier: MIT
pragma solidity 0.8.36;
import {AccessControl} from "@openzeppelin/contracts/access/AccessControl.sol";
import {ReentrancyGuard} from "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
import {IMoncorVault} from "./interfaces/IMoncorVault.sol";

contract MoncorVault is AccessControl,ReentrancyGuard,IMoncorVault {
 bytes32 public constant ROUTER_ROLE=keccak256("ROUTER_ROLE");bytes32 public constant TREASURY_ROLE=keccak256("TREASURY_ROLE");bytes32 public constant FEE_PAUSER_ROLE=keccak256("FEE_PAUSER_ROLE");
 address public immutable treasury;bool public routerConfigured;bool public feeWithdrawalPaused;uint256 public lockedStake;uint256 public reservedPayout;uint256 public claimableLiability;uint256 public refundableLiability;uint256 public protocolFeesAccrued;
 struct Entitlement{address beneficiary;uint128 amount;bool refund;}mapping(bytes32=>Entitlement) public entitlements;mapping(bytes32=>uint128) public wagerStake;mapping(bytes32=>uint128) public wagerReserve;
 error UnsupportedAsset(address);error InvalidValue(uint256,uint256);error InsufficientReserve(uint256,uint256);error EntitlementExists(bytes32);error NoEntitlement(bytes32);error WrongBeneficiary();error TransferFailed();error Insolvent(uint256,uint256);error FeeWithdrawalIsPaused();
 event ReserveFunded(address indexed funder,uint256 amount);event PayoutAccrued(bytes32 indexed wagerId,address indexed player,uint128 amount,uint128 fee);event RefundAccrued(bytes32 indexed wagerId,address indexed player,uint128 amount);event Claimed(bytes32 indexed wagerId,address indexed player,uint128 amount,bool refund);event ProtocolFeesWithdrawn(address indexed treasury,uint256 amount);event FeeWithdrawalPauseChanged(bool paused);
 constructor(address admin,address treasury_){require(admin!=address(0)&&treasury_!=address(0));treasury=treasury_;_grantRole(DEFAULT_ADMIN_ROLE,admin);_grantRole(TREASURY_ROLE,treasury_);_grantRole(FEE_PAUSER_ROLE,admin);}
 function configureRouter(address router) external onlyRole(DEFAULT_ADMIN_ROLE){require(router!=address(0)&&!routerConfigured);routerConfigured=true;_grantRole(ROUTER_ROLE,router);}
 function setFeeWithdrawalPaused(bool value) external onlyRole(FEE_PAUSER_ROLE){feeWithdrawalPaused=value;emit FeeWithdrawalPauseChanged(value);}
 function fundReserve() external payable{require(msg.value>0);emit ReserveFunded(msg.sender,msg.value);}receive() external payable{emit ReserveFunded(msg.sender,msg.value);}
 function protectedBalance() public view returns(uint256){return claimableLiability+refundableLiability+reservedPayout+protocolFeesAccrued;}
 function freeReserve() public view returns(uint256){uint256 p=protectedBalance();return address(this).balance>p?address(this).balance-p:0;}
 function withdrawableProtocolFees() public view returns(uint256){if(feeWithdrawalPaused)return 0;uint256 nonFee=claimableLiability+refundableLiability+reservedPayout;if(address(this).balance<=nonFee)return 0;uint256 liquid=address(this).balance-nonFee;return liquid<protocolFeesAccrued?liquid:protocolFeesAccrued;}
 function lockStake(bytes32 id,address,address asset,uint128 stake,uint128 maxPayout) external payable onlyRole(ROUTER_ROLE){if(asset!=address(0))revert UnsupportedAsset(asset);if(msg.value!=stake)revert InvalidValue(stake,msg.value);if(wagerStake[id]!=0)revert EntitlementExists(id);uint256 available=address(this).balance-(claimableLiability+refundableLiability+reservedPayout+protocolFeesAccrued);if(available<maxPayout)revert InsufficientReserve(maxPayout,available);wagerStake[id]=stake;wagerReserve[id]=maxPayout;lockedStake+=stake;reservedPayout+=maxPayout;_assertSolvent();}
 function accruePayout(bytes32 id,address player,uint128 payout,uint128 fee) external onlyRole(ROUTER_ROLE){if(entitlements[id].amount!=0)revert EntitlementExists(id);uint128 reserve=wagerReserve[id];uint128 stake=wagerStake[id];require(uint256(payout)+fee<=reserve);wagerReserve[id]=0;wagerStake[id]=0;reservedPayout-=reserve;lockedStake-=stake;protocolFeesAccrued+=fee;if(payout>0){entitlements[id]=Entitlement(player,payout,false);claimableLiability+=payout;}emit PayoutAccrued(id,player,payout,fee);_assertSolvent();}
 function accrueRefund(bytes32 id,address player,uint128 amount) external onlyRole(ROUTER_ROLE){if(entitlements[id].amount!=0)revert EntitlementExists(id);uint128 reserve=wagerReserve[id];uint128 stake=wagerStake[id];require(amount==stake);wagerReserve[id]=0;wagerStake[id]=0;reservedPayout-=reserve;lockedStake-=stake;entitlements[id]=Entitlement(player,amount,true);refundableLiability+=amount;emit RefundAccrued(id,player,amount);_assertSolvent();}
 function claimTo(bytes32 id,address beneficiary) external onlyRole(ROUTER_ROLE) nonReentrant returns(uint256 amount){Entitlement memory e=entitlements[id];if(e.amount==0)revert NoEntitlement(id);if(e.beneficiary!=beneficiary)revert WrongBeneficiary();delete entitlements[id];amount=e.amount;if(e.refund)refundableLiability-=amount;else claimableLiability-=amount;(bool ok,)=payable(beneficiary).call{value:amount}("");if(!ok)revert TransferFailed();emit Claimed(id,beneficiary,e.amount,e.refund);}
 function withdrawProtocolFees(uint256 amount) external onlyRole(TREASURY_ROLE) nonReentrant{if(feeWithdrawalPaused)revert FeeWithdrawalIsPaused();if(amount>withdrawableProtocolFees())revert Insolvent(address(this).balance,claimableLiability+refundableLiability+reservedPayout+amount);protocolFeesAccrued-=amount;uint256 postBalance=address(this).balance-amount;if(postBalance<protectedBalance())revert Insolvent(postBalance,protectedBalance());(bool ok,)=payable(treasury).call{value:amount}("");if(!ok)revert TransferFailed();emit ProtocolFeesWithdrawn(treasury,amount);}
 function solvency(address asset) external view returns(uint256 balance,uint256 liabilities,uint256 reserve){if(asset!=address(0))revert UnsupportedAsset(asset);return(address(this).balance,claimableLiability+refundableLiability+protocolFeesAccrued,reservedPayout);}
 function _assertSolvent() internal view{uint256 required=protectedBalance();if(address(this).balance<required)revert Insolvent(address(this).balance,required);}
}
